plugin 'cocoapods-pod-linkage'
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'


# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
#  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  pod "FSLPromisesObjC", :linkage => :dynamic
  pod "FMDB", :linkage => :dynamic
     
  pod "FreestarAds-AdColony", "~> 4.7.2.1"
  pod "FreestarAds-AppLovin", "~> 11.11.3.3"
  pod "FreestarAds-AppLovinMax", "~> 11.11.3.4"
  pod "FreestarAds-Criteo", "~> 4.3.1.1"
  pod "FreestarAds-Fyber2", "~> 8.2.4.3"
  pod 'FreestarAds-GAM', '~> 10.9.0.7'
  pod 'FreestarAds-GAM/Facebook', '~> 10.9.0.7'
  pod 'FreestarAds-Googleadmob', '~> 10.9.0.7'
  pod 'FreestarAds-Googleadmob/Facebook', '~> 10.9.0.7'
  pod "FreestarAds-Hyprmx", "~> 6.0.3.4"
  pod "FreestarAds-Ogury", "~> 2.1.0.3"
  pod "FreestarAds-Prebid", "~> 2.1.5.13"
  pod "FreestarAds-TAM", "~> 4.7.5.7"
  pod "FreestarAds-Unity", "~> 4.8.0.5"
  pod "FreestarAds-Yahoo", "~> 1.14.2.2"
  pod "FreestarAds-Nimbus", "~> 2.15.0.5"
  pod "FreestarAds-Smaato", "~> 22.1.3.1"
  pod "FreestarAds-Vungle", "~> 7.0.1.3"

end

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end
#   installer.pods_project.build_configurations.each do |config|
#     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#     config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
#     installer.pods_project.build_settings(config.name)['VALID_ARCHS'] = ["arm64 arm64e armv7 armv7s x86_64"]
#   end
end
